### ISSUE TITLE
Can we use this for ignitespeak?

### ISSUE THREAD

**Issue by subelsky** [IgniteTalks/ignite-submission-site#1]
Would love to marry your nice front-end design to our back-end code, [ignitespeak](https://github.com/ignitebaltimore/ignitespeak)...is this open source? If you're game for it, I can also send a pull request with a license file that clarifies the issue (such as creative commons, MIT license, etc.)

**Comment by slead** [comment]
Hi Mike,

Go for it! I just added an MIT license file.

Cheers,
Steve
